GoonListados/Models/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GoonListados.Models
{
    public class DataItem
    {
        public String datos1;
        public String datos2;
        public String datos3;
        public String datos4;
        public String datos5;
        public String datos6;
    }
}

GoonListados/Controllers/BusesController.cs
using GoonListados.Helpers;
using GoonListados.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace GoonListados.Controllers
{
    public class BusesController : Controller
    {
        // GET: Buses
        public ActionResult Index()
        {
            List<DataItem> _list = DataHelper.p_GetData("Buses");

            return View(_list);
        }

        [HttpGet]
        public ActionResult Ver(int id)
        {
            ViewBag.Title = "Buses | Ver >>> " + id.ToString();

            return View();
        }
    }
}

GoonListados/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoonListados.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

GoonListados/Controllers/RoutersController.cs
using GoonListados.Helpers;
using GoonListados.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace GoonListados.Controllers
{
    public class RoutersController : Controller
    {
        // GET: Routers
        public ActionResult Index()
        {
            List<DataItem> _list = DataHelper.p_GetData("Routers");

            return View(_list);
        }

        [HttpGet]
        public ActionResult Ver(int id)
        {
            ViewBag.Title = "Routers | Ver >>> " + id.ToString();

            return View();
        }
    }
}

GoonListados/Controllers/SimsController.cs
using GoonListados.Helpers;
using GoonListados.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GoonListados.Controllers
{
    public class SimsController : Controller
    {
        // GET: Sims
        public ActionResult Index()
        {
            //List<DataItem> _list = DataHelper.p_GetData("Sims");
            List<DataItem> _list = new List<DataItem>();

            String _s = ConfigurationManager.ConnectionStrings["ConnectionDefault"].ConnectionString;

            SqlConnection _conn = new SqlConnection(_s);
            SqlCommand _command = new SqlCommand("SELECT * FROM Noticias", _conn);

            _conn.Open();           

            SqlDataReader _dr = _command.ExecuteReader();

            while (_dr.Read()) {

                _list.Add(new DataItem() {
                    datos1 =  _dr.GetValue(0).ToString(),
                    datos2 = _dr.GetValue(1).ToString(),
                    datos3 = _dr.GetValue(2).ToString(),
                    datos4 = _dr.GetValue(3).ToString(),
                    datos5 = "<< sin datos >>",
                    datos6 = "<< sin datos >>"

                });
            }

                _conn.Close();

            return View(_list);
        }

        [HttpGet]
        public ActionResult Ver(int id)
        {
            ViewBag.Title = "Sims | Ver >>> " + id.ToString();

            return View();
        }
    }
}

GoonListados/Views/Buses/Index.cshtml
@using GoonListados.Models
@model List<GoonListados.Models.DataItem>


@{
    ViewBag.Title = "Buses";
}


@Html.Partial("~/Views/Shared/_Filter.cshtml")

<div class="card mb-3">


    <div class="card-header">
        <i class="fas fa-table"></i>
        Ejemplo tabla @ViewBag.Title
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Age</th>
                        <th>Start date</th>
                        <th>Salary</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Age</th>
                        <th>Start date</th>
                        <th>Salary</th>
                    </tr>
                </tfoot>

                <tbody>

                    @{ var index = 1; }

                    @foreach (DataItem _item in Model)
                    {
                        <tr>
                            <td>@_item.datos1</td>
                            <td>@_item.datos2</td>
                            <td>@_item.datos3</td>
                            <td>@_item.datos4</td>
                            <td>@_item.datos5</td>
                            <td>@_item.datos6</td>
                            <td>
                                @Html.ActionLink("Ver", "Ver", "Buses", new { id = index }, new { @class = "btn btn-primary" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

GoonListados/Views/Buses/Ver.cshtml
<h2>Ver</h2>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>


<div class="row" style="margin-bottom: 9px;">

    <div class="col">
        <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#infoModalNotas"><span class="badge badge-light" style="margin-left:5px;"> 4 </span><span class="float-left"> Notas </span></a>
        <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#infoModalUbicaciones"><span class="badge badge-light" style="margin-left:5px;"> 8 </span><span class="float-left">Ubicaciones</span></a>
    </div>

    <div class="col">
        @Html.ActionLink("Volver", "Index", "Buses", new { @class = "btn btn-primary float-right" })
    </div>

</div>




<!-- Modal - Notas-->
<div class="modal fade" id="infoModalNotas" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Notas: @ViewBag.Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Col 1</th>
                            <th scope="col">Col 2</th>
                            <th scope="col">Col 3</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">2</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                        <tr>
                            <th scope="row">4</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal - Ubicaciones-->
<div class="modal fade" id="infoModalUbicaciones" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ubicaciones: @ViewBag.Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Col 1</th>
                            <th scope="col">Col 2</th>
                            <th scope="col">Col 3</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">2</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                        <tr>
                            <th scope="row">4</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

GoonListados/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicio";
}

<!-- Icon Cards-->
<div class="row">
    <div class="col-xl-4 col-sm-12 mb-4">
        <div class="card text-white bg-primary o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-bus"></i>
                </div>
                <div class="mr-5">26 New buses!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#" data-toggle="modal" data-target="#infoModal">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="col-xl-4 col-sm-12 mb-4">
        <div class="card text-white bg-warning o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-wifi"></i>
                </div>
                <div class="mr-5">11 New Routers!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#" data-toggle="modal" data-target="#infoModal">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="col-xl-4 col-sm-12 mb-4">
        <div class="card text-white bg-success o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-mobile"></i>
                </div>
                <div class="mr-5">123 New Sims!</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="#" data-toggle="modal" data-target="#infoModal">
                <span class="float-left">View Details</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
</div>


<!-- Modal-->
<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Modal @ViewBag.Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ultrices dictum diam, eget rhoncus odio pharetra at. Donec fermentum arcu turpis. Mauris accumsan interdum urna, vel ultrices orci hendrerit vitae. Donec sodales semper velit et accumsan. Praesent non dui purus. Praesent condimentum fringilla purus, vel cursus ante fringilla hendrerit. Mauris hendrerit metus id nisl blandit, semper imperdiet mi ultrices. Fusce accumsan at sem aliquam mollis. Phasellus metus ligula, dictum a vulputate et, molestie accumsan neque. Donec blandit lectus sit amet est hendrerit luctus. Suspendisse id neque luctus, tincidunt dui sit amet, venenatis nulla. Mauris non molestie tellus. Donec tristique justo lacus, eget suscipit ex gravida quis. Curabitur interdum lobortis nisl, et posuere velit laoreet et.</p>
                <p>Praesent laoreet purus vitae euismod tempus. Donec ut ligula commodo, ullamcorper diam nec, elementum justo. Praesent at lobortis tortor. Praesent iaculis consectetur aliquet. Quisque dignissim ut ipsum sit amet vestibulum. Nam aliquam tincidunt bibendum. Vivamus nec blandit ante.</p>                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

GoonListados/Views/Routers/Index.cshtml
@using GoonListados.Models
@model List<GoonListados.Models.DataItem>


@{
    ViewBag.Title = "Routers";
}


@Html.Partial("~/Views/Shared/_Filter.cshtml")


<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Ejemplo tabla @ViewBag.Title
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Age</th>
                        <th>Start date</th>
                        <th>Salary</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Position</th>
                        <th>Office</th>
                        <th>Age</th>
                        <th>Start date</th>
                        <th>Salary</th>
                    </tr>
                </tfoot>

                <tbody>

                    @{ var index = 1; }

                    @foreach (DataItem _item in Model)
                    {
                        <tr>
                            <td>@_item.datos1</td>
                            <td>@_item.datos2</td>
                            <td>@_item.datos3</td>
                            <td>@_item.datos4</td>
                            <td>@_item.datos5</td>
                            <td>@_item.datos6</td>
                            <td>
                                @Html.ActionLink("Ver", "Ver", "Routers", new { id = index }, new { @class = "btn btn-primary" })
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>

GoonListados/Views/Routers/Ver.cshtml
<h2>Ver</h2>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>


<div class="row" style="margin-bottom: 9px;">

    <div class="col accordion" id="accordionExample">
        <div class="card" style="margin-bottom: 9px;">
            <div class="card-header" id="headingOne">
                <h5 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Notas
                    </button>
                </h5>
            </div>

            <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                <div class="card-body">

                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Col 1</th>
                                <th scope="col">Col 2</th>
                                <th scope="col">Col 3</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">2</th>
                                <td>Datos 1</td>
                                <td>Datos 2</td>
                                <td>Datos 3</td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Datos 1</td>
                                <td>Datos 2</td>
                                <td>Datos 3</td>
                            </tr>
                            <tr>
                                <th scope="row">4</th>
                                <td>Datos 1</td>
                                <td>Datos 2</td>
                                <td>Datos 3</td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="headingTwo">
                <h5 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Ubicaciones
                    </button>
                </h5>
            </div>
            <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                <div class="card-body">
                    <table class="table table-sm">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">Col 1</th>
                                <th scope="col">Col 2</th>
                                <th scope="col">Col 3</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <th scope="row">2</th>
                                <td>Datos 1</td>
                                <td>Datos 2</td>
                                <td>Datos 3</td>
                            </tr>
                            <tr>
                                <th scope="row">3</th>
                                <td>Datos 1</td>
                                <td>Datos 2</td>
                                <td>Datos 3</td>
                            </tr>
                            <tr>
                                <th scope="row">4</th>
                                <td>Datos 1</td>
                                <td>Datos 2</td>
                                <td>Datos 3</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

</div>

GoonListados/Views/Shared/_Breadcrumbs.cshtml
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">GoonListados</a>
    </li>
    <li class="breadcrumb-item active">@ViewBag.Title</li>
</ol>

GoonListados/Views/Sims/Ver.cshtml
<h2>Ver</h2>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>

<div class="row" style="margin-bottom: 9px;">

    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>
    <div class="col"><input type="text" class="form-control" placeholder="Datos"></div>

</div>


<div class="row" style="margin-bottom: 9px;">

    <div class="col">
        <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#infoModalNotas"><span class="badge badge-light" style="margin-left:5px;"> 4 </span><span class="float-left"> Notas </span></a>
        <a class="btn btn-primary" href="#" data-toggle="modal" data-target="#infoModalUbicaciones"><span class="badge badge-light" style="margin-left:5px;"> 8 </span><span class="float-left">Ubicaciones</span></a>
    </div>

    <div class="col">
        @Html.ActionLink("Volver", "Index", "Sims", new { @class = "btn btn-primary float-right" })
    </div>

</div>




<!-- Modal - Notas-->
<div class="modal fade" id="infoModalNotas" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Notas: @ViewBag.Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Col 1</th>
                            <th scope="col">Col 2</th>
                            <th scope="col">Col 3</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">2</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                        <tr>
                            <th scope="row">4</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal - Ubicaciones-->
<div class="modal fade" id="infoModalUbicaciones" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Ubicaciones: @ViewBag.Title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Col 1</th>
                            <th scope="col">Col 2</th>
                            <th scope="col">Col 3</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">2</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                        <tr>
                            <th scope="row">3</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                        <tr>
                            <th scope="row">4</th>
                            <td>Datos 1</td>
                            <td>Datos 2</td>
                            <td>Datos 3</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>